title: Project 

pages: false

fields:
  title:
    label: Title
    type: title
    required: true
    
  abstract:
    label: Abstract
    type: textarea
    required: true
  
  myImage:
    label: Main Image
    type: image

  gallery:
    label: Gallery
    type: structure
    entry:
      {{image}}
    fields:
      image:
        label: Image
        type: image

  authors:
    label: Author(s)
    type: structure
    required: true
    entry:
      {{name}}<br />
      {{link}}
    fields:
      name:
        label: Name
        type: text
      link:
        label: Link
        type: url

  date:
    label: Date
    type: date
    format: MM/DD/YYYY
    required: true

  tags:
    label: My Tags
    type: tags
  
  sources:
    label: Sources
    type: structure
    entry:
      {{source}}
    fields:
      image:
        label: Source
        type: url