title: Project 

pages: false

fields:
  title:
    label: Title
    type: title
    required: true
    
  abstract:
    label: Abstract
    type: textarea
    required: true
  
  image:
    label: Image
    type: image

  authors:
    label: Author(s)
    type: structure
    required: true
    entry:
      {{name}}<br />
      {{link}}
    fields:
      name:
        label: Name
        type: text
      link:
        label: Link
        type: url

  date:
    label: Date
    type: date
    format: MM/DD/YYYY
    required: true

  tags:
    label: My Tags
    type: tags
  
  source:
    label: Source
    type: url